# fly.toml app configuration file generated for mixboard-dj on 2026-09-20T00:01:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mixboard-dj'
primary_region = 'dfw'

[[mounts]]
  source = 'mixboard_data'
  destination = '/app/storage'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
